name: merge_workflow

on:
    pull_request:
    types: [opened, synchronize, reopened, closed]

on:
  pull_request: # Se déclenche uniquement pour les Merge Requestssssss

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Lint code
        run: npm run lint

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Build .NET app
        run: dotnet build -c Release
